# system setup
sudo: required

# setup language
language: go
go:
  - "1.11"

install:
  - go get golang.org/x/tools/cmd/cover github.com/mattn/goveralls ./...

script:
  - go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
